Refactor: Using Kafka instead of RabbitMQ
west2-online/fzuhelper-server pull request #33
Opened 2024-10-16 09:38 UTC by mutezebra

Using Kafka instead of RabbitMQ
Refs: #30

2024-10-16 09:40 UTC, mutezebra commented
编写函数已经过验证
![image](https://github.com/user-attachments/assets/4eea0370-1ab2-47d3-80c1-c41f7bf7bfe3)

2024-10-16 09:44 UTC, mutezebra commented
Kafka的日志管理同样可以利用EsHook，而且可以区分正常的Logger与ErrLogger，我在想我们是否需要这个。
如有需要可以评论留言，我再更改EsHook相关的PR

2024-10-16 16:31 UTC, ozline requested changes

2024-10-16 16:31 UTC, ozline commented on config/config.example.yaml
删了rabbitmq的，kafka的去哪了

2024-10-16 16:31 UTC, ozline commented on docker/docker-compose.yml
> +#  kafka:
这个不用注释，取消掉就好，环境变量参考其他的service，用一个统一的env文件保存

2024-10-16 16:31 UTC, ozline commented on cmd/template/dal/mq/init.go
> +func NewReader(topic string) *kafka.Reader {
这个new丢到pkg里，里面常量丢到constants里然后引用，当然函数名最好改一下，记得加注释

2024-10-16 16:31 UTC, ozline commented on cmd/template/dal/mq/init.go
> +func NewWriter() *kafka.Writer {
同理

2024-10-16 16:31 UTC, ozline commented on cmd/template/dal/mq/init.go
> +func GetConn() *kafka.Conn {
同

2024-10-16 16:31 UTC, ozline commented
> Kafka的日志管理同样可以利用EsHook，而且可以区分正常的Logger与ErrLogger，我在想我们是否需要这个。
> 
> 如有需要可以评论留言，我再更改EsHook相关的PR

ok

2024-10-18 09:16 UTC, SchwarzSail commented
感觉也可以合掉了

2024-10-18 13:14 UTC, ozline commented on docker/env/kafka.env
> +ALLOW_PLAINTEXT_LISTEN
这是什么？允许 PLAINTECT_LISTEN？

2024-10-20 08:11 UTC, ozline approved these changes

2024-10-21 11:10 UTC, merged