Add CD Workflow
west2-online/fzuhelper-server pull request #63
Opened 2024-10-26 12:36 UTC by SchwarzSail

个人仓库已通过部署测试
closes #58

2024-10-27 03:33 UTC, SchwarzSail commented
@renbaoshuo @jiuxia211 ccccccccccccccc

2024-10-27 04:41 UTC, ozline commented on hack/entrypoint.sh
> +# you may obtain a copy of the License at
这个地方为什么做了修改？

2024-10-27 04:41 UTC, ozline commented on hack/entrypoint.sh
> +sh "$OUTPUT_PATH/$SERVICE/bootstrap.sh" --etcd-addr="fzu-helper-etcd:2379"
我一直在想，你这个参数能传过去吗？

2024-10-27 06:37 UTC, SchwarzSail commented on hack/docker-run.sh
> +    docker rm -f "$container_name"
我的问题，当时为了方便忘记改回来了）

2024-10-27 06:37 UTC, SchwarzSail commented on hack/entrypoint.sh
> +sh "$OUTPUT_PATH/$SERVICE/bootstrap.sh" --etcd-addr="fzu-helper-etcd:2379"
测试了一下，确实没传过去，我认为不如直接用 export 导出环境变量清楚一些

2024-10-27 08:16 UTC, SchwarzSail commented
@ozline cccc

2024-10-28 00:46 UTC, jiuxia211 approved these changes
LGTM

2024-10-28 10:50 UTC, ozline requested changes
把看到的改一下

2024-10-28 10:50 UTC, ozline commented on .github/workflows/deploy.yaml
> +      - name: SSH and deploy on server
这边有没有尝试用 ssh action？

2024-10-28 10:50 UTC, ozline commented on cmd/classroom/main.go
> +	etcdAddr = os.Getenv("ETCD_ADDR")
这个 etcdAddr 不用在这里获取，把整个过程丢到 config Init 里去，然后把这个 Init 的第一个参数去掉，没必要

2024-10-28 10:50 UTC, ozline commented on cmd/classroom/main.go
> +	etcdAddr = os.Getenv("ETCD_ADDR")
其他模块顺便也做了吧，既然你这个 pr 涉及到这个的修改，就一并改掉

然后把 pr title 改一下，说明涉及到这个改动

2024-10-28 10:50 UTC, ozline commented on docker/Dockerfile
> +ENV ETCD_ADDR=fzu-helper-etcd:2379
这个用传参，你在这边写死了后面要改不方便

docker run 的时候是可以指定特殊参数的

2024-10-28 10:50 UTC, ozline commented on hack/entrypoint.sh
你把这个删了，怎么本地调试？

2024-10-28 10:56 UTC, SchwarzSail commented on hack/entrypoint.sh
昨天有说过如果新开一个脚本去启动的话会有 can't open config.yaml 的报错

2024-10-28 10:58 UTC, SchwarzSail commented on cmd/classroom/main.go
> +	etcdAddr = os.Getenv("ETCD_ADDR")
> 这个 etcdAddr 不用在这里获取，把整个过程丢到 config Init 里去，然后把这个 Init 的第一个参数去掉，没必要

肯定的，这边相当于一个草稿，让你看一下这样写行不行

2024-10-28 10:58 UTC, SchwarzSail commented on docker/Dockerfile
> +ENV ETCD_ADDR=fzu-helper-etcd:2379
我试一下用 docker run

2024-10-28 11:14 UTC, ozline commented on docker/Dockerfile
> +ENV ETCD_ADDR=fzu-helper-etcd:2379
> 我试一下用 docker run

对，你了解一下给容器传参就很好理解，我印象里是在Dockerfile里改

2024-10-28 11:17 UTC, ozline commented on hack/entrypoint.sh
> open

这个脚本的作用就像它的名字一样，作为程序的入口脚本，这个和bootstrap其实是一个意思，但是我没有去修改bootstrap

我前些天开了一个新issue，期望可以调整一下这样的运行方式，规避掉bootstrap，使用我们自己的“bootstrap”，即entrypoint，在这里只是做一个程序启动时的环境变量设计，不会涉及config载入，你要做的就是把这里涉及config读取的代码去掉

你前面说config打开报错，实际上我猜测是程序运行时尝试载入但是失败了。你或许本地没有重新构建项目

2024-10-28 11:30 UTC, SchwarzSail commented on hack/entrypoint.sh
我再重新试一下

2024-10-28 11:50 UTC, SchwarzSail commented
closes #69

2024-10-28 18:46 UTC, ozline requested changes

2024-10-28 18:46 UTC, ozline commented on hack/entrypoint.sh
> +export ETCD_ADDR="fzu-helper-etcd:2379"
我想你没有理解我的意思

我举个例子，假设现在服务器有 3 台，你还能写死这个 ETCD_ADDR 为这个吗？

2024-10-28 18:46 UTC, ozline commented on hack/entrypoint.sh
> +export ETCD_ADDR="fzu-helper-etcd:2379"
https://github.com/ozline/tiktok/blob/main/Dockerfile 这个文件的line21

https://github.com/ozline/tiktok/blob/main/docker-run.sh 这个文件的 line47

2024-10-28 18:46 UTC, ozline commented on hack/entrypoint.sh
> +export ETCD_ADDR="fzu-helper-etcd:2379"
然后你需要确认一下，我们 makefile 中的 make xxx 到底能不能用

2024-10-29 02:52 UTC, SchwarzSail commented on hack/entrypoint.sh
> +export ETCD_ADDR="fzu-helper-etcd:2379"
> 我想你没有理解我的意思
> 
> 我举个例子，假设现在服务器有 3 台，你还能写死这个 ETCD_ADDR 为这个吗？

我目前的想法是 entrypoint 导出的这个ETCD_ADDR 变量是 default值
想要更改应该可以通过 docker run -e 参数进行覆盖
你之前说过地址一旦确定了就尽量不再更改了，在 k8s 中可以通过 service 名进行域名解析到底层的 pod，所以和多少台服务器没有关系罢

2024-10-29 09:07 UTC, ozline approved these changes

2024-10-29 09:10 UTC, merged