add build.md and modify README.md ,deploy.md for new architecture
west2-online/fzuhelper-server pull request #73
Opened 2024-10-31 14:03 UTC by SchwarzSail

添加 build.md 说明构建项目的大致流程
修改了 README.md 适应新架构
删除了 deploy.md 中的云服务部署部分，因为云服务部署已经实现了自动化，具体直接参考deploy.yaml

2024-10-31 15:00 UTC, ozline commented
帮 @mutezebra format 一下 env_explain.md 吧

2024-10-31 15:06 UTC, ozline commented on docs/README.zh.md
en 版的也要改一下，
然后这个文件少了个树的 header 和 footer，你可以按照 `tree`命令的输出格式来修改一下

2024-10-31 15:06 UTC, ozline commented on docs/build.md
> +4. 读取 config.yaml 中的配置，完成初始化
这边可以细化一下，比如我们的 main.go 具体都做了些什么

这边需要画点图，我知道很麻烦，但是画完图会很清晰。可以用 [excalidraw](https://excalidraw.com/) 来画

2024-10-31 15:06 UTC, ozline commented on docs/build.md
> +构建过程主要通过 `build.sh` 脚本完成，用于编译指定服务模块的二进制文件或进行系统测试。
需要说明一下这个 build.sh 位于哪里，一个好用的解决方案是给这个加链接

2024-10-31 15:06 UTC, ozline commented on docs/build.md
> +启动过程主要通过 `entrypoint.sh` 脚本完成。
同上

2024-10-31 15:06 UTC, ozline commented on docs/build.md
这个文件说明了一些构建的流程，你可以在一级标题下面简单说明一下这个文档的作用

启动流程有点过于简单了，这里可以以本地 dev 环境启动为例，介绍一下 `make xxx` 具体的执行流程，用个图表示比较好，然后附带说明

2024-10-31 15:06 UTC, ozline commented on docs/deploy.md
Deploy 的视角并不清晰，这里麻烦直接以一名“要部署本项目的 west2-online member”的视角来说明

同样的，需要在一级标题下面简单说明一下这个文档的内容以及角度

然后我们需要以“一台全新的服务器”为 bg，介绍怎么部署这个项目

2024-10-31 15:07 UTC, renbaoshuo requested changes
我先 block 住这个 PR，让我修改一下格式

2024-10-31 15:13 UTC, renbaoshuo commented on docs/build.md
> +4. 读取 config.yaml 中的配置，完成初始化
我记得 GitHub 是支持 mermaid 的。

2024-10-31 15:20 UTC, renbaoshuo commented on docs/build.md
> +4. 读取 config.yaml 中的配置，完成初始化
我记得 GitHub 是支持 mermaid 的。

2024-11-01 08:55 UTC, ozline commented
再补充一个develop指南吧_(:з」∠)_正好我帮你补了classroom，你按照现在的设计写一篇挺好的

2024-11-01 08:59 UTC, ozline commented on README.md
>  ```bash
这个目录树没更新

2024-11-01 08:59 UTC, ozline commented on docs/deploy.md
>  ## 本地部署
这个是本地开发环境构建_(:з」∠)_

deploy指的是部署到server侧

不过既然写了就留着吧，后面再加一个如何部署到一个新开的服务器上（也就是说这个服务器上除了原始系统啥也没有）

2024-11-01 09:54 UTC, SchwarzSail commented
> 再补充一个develop指南吧_(:з」∠)_正好我帮你补了classroom，你按照现在的设计写一篇挺好的

develop 指南是神魔

2024-11-01 12:42 UTC, ozline commented
> > 再补充一个develop指南吧_(:з」∠)_正好我帮你补了classroom，你按照现在的设计写一篇挺好的
> 
> develop 指南是神魔

就是对于负责新模块的同学来说应该怎么开始写代码的文档

2024-11-01 15:52 UTC, renbaoshuo requested changes
还是存在一些问题：

1. 操作过程描述不够清晰：需要站在读者的角度重新考虑，细节要到位，比如我修改的上传文件部分，需要提及使用什么工具上传
2. 尽量避免出现「你」「您」等人称代词，应删尽删，实在不行用「我们」，营造距离感。要有那种客观的感觉。
3. Markdown 格式需要格外注意。我个人常用 Prettier 进行格式化。中西文字符之间需要使用空格分隔，等等。

2024-11-01 15:52 UTC, renbaoshuo commented on docs/deploy.md
> +
GPT 味好重……

2024-11-01 15:52 UTC, renbaoshuo commented on docs/deploy.md
> +在本机和服务器上都要登录阿里云的docker仓库
本机是指什么？

2024-11-01 17:15 UTC, ozline commented on docs/build.md
> +构建过程主要通过 [build.sh](../docker/script/build.sh) 脚本完成，用于编译指定服务模块的二进制文件或进行系统测试。
前面补充一下我们如何触发构建流程，如何从 Makefile 到 build.sh

2024-11-01 17:15 UTC, ozline commented on docs/build.md
> +启动过程主要通过 [entrypoint.sh](/docker/script/entrypoint.sh) 脚本完成。
前面同样补充一下我们如何触发这个 `entrypoint.sh`，因为这个文件和`build.sh`都不是让人自己调用的，这么写的话会让人误以为是直接调用这个就可以

2024-11-01 17:15 UTC, ozline commented on docs/deploy.md
> +现在切换到开发机上，cd 到项目的根目录下，然后执行以下命令：
冒号去掉，这部分写的挺好的，就是缺一个流程图

实际上服务端部署部分涉及到了本机推送镜像、服务器在再拉镜像做更新，有一个图的话会更好理解，样例图我会发在重构群里

2024-11-01 17:15 UTC, ozline commented on docs/deploy.md
> +│   └── docker-run.sh
为什么这个树的底端永远不是闭合的。。`├──`不就好了

接下来顶端是不是缺少了点什么？
一般不都是
```text
.
├── CODEOWNERS
├── LICENSE
├── Makefile
├── README.md
```
这样吗？你按照`tree`输出的来

2024-11-02 11:08 UTC, SchwarzSail commented on docs/deploy.md
> +│   └── docker-run.sh
“这个树的底端永远不是闭合的”是啥意思
这边只给出大概的一个目录结构，应该不需要特别完整吧

2024-11-02 11:53 UTC, ozline commented
这个文档后续我自己改一下，今晚我直接合进去，然后有什么需要修改的话后面再说，时间有点久了

2024-11-02 12:43 UTC, renbaoshuo commented
> 这个文档后续我自己改一下，今晚我直接合进去，然后有什么需要修改的话后面再说，时间有点久了

你记得喊我 approve 一下，我现在是 block 住它的状态

2024-11-02 13:31 UTC, ozline commented
@renbaoshuo review 一下没啥事的话就合掉，develop 文档后续开一个新 pr 把 @SchwarzSail 辛苦两位了

2024-11-03 11:59 UTC, renbaoshuo approved these changes
我又改了改。现在看起来差不多了。

PS: 你们行末怎么都不加句号...

2024-11-03 12:09 UTC, merged