feat: add url  in api service
west2-online/fzuhelper-server pull request #75
Opened 2024-11-01 15:25 UTC by penqee

添加了一系列调用原136容器相关接口进行调用的函数
对于得到其响应的处理不进行包装(pack)
TestSetting 缺少数据，还未完成测试，其余皆测试过了

2024-11-01 17:06 UTC, ozline requested changes
问题有点严重啊，让 @jiuxia211 赶紧来带一下你

2024-11-01 17:06 UTC, ozline commented on pkg/base/client/hz.go
这个 client 是用来做什么的？

2024-11-01 17:06 UTC, ozline commented on idl/api.thrift
还好你先提交上来了，你先把 thrift 文件写完了，再去写对应的逻辑，这不是一个合规的开发流程

2024-11-01 17:06 UTC, ozline commented on cmd/api/main.go
> +	api.HzClient, err = client.NewHzClient()
为什么要在 api server 上开一个 hzclient？

2024-11-01 17:13 UTC, jiuxia211 commented on cmd/api/main.go
> +	api.HzClient, err = client.NewHzClient()
因为要访问本地python 的接口啊

2024-11-01 17:16 UTC, jiuxia211 commented
我记得这个url 不是有对应的前端吗? 有没有测试过

2024-11-01 18:17 UTC, jiuxia211 commented on idl/api.thrift
也许对应的接口 请求 就是空的，然后需要返回文件，没有合适的response

2024-11-02 02:50 UTC, penqee commented on cmd/api/main.go
> +	api.HzClient, err = client.NewHzClient()
> 因为要访问本地python 的接口，但 在这里开client 是否合理有待商榷

开个client才能发请求给本地python接口，所以要开个hzclient

2024-11-02 02:54 UTC, penqee commented on idl/api.thrift
> 也许对应的接口 请求 就是空的，然后需要返回文件，没有合适的response

136的python代码的response，在某些函数里不一定是固定的，有的是错误时返回字符串，正确情况返回json格式的

2024-11-02 02:59 UTC, penqee commented on idl/api.thrift
> 也许对应的接口 请求 就是空的，然后需要返回文件，没有合适的response

那些空请求，的确是只要发个请求就好了，不需要再传参数

2024-11-02 03:01 UTC, penqee commented
> 我记得这个url 不是有对应的前端吗? 有没有测试过

我先按照url提供的url进行测试了，测试完成后，再测试自己写的代码，然后比对看结果的

2024-11-03 12:47 UTC, jiuxia211 approved these changes

2024-11-03 13:01 UTC, merged